version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3
     steps:
       - checkout
       - restore_cache:
           key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
       - run:
           name: Install dependencies
           command: |
             sudo pip install virtualenv
             virtualenv venv
             . venv/bin/activate
             pip install -r requirements.txt
             pip install -r requirements-dev.txt
       - save_cache:
           key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
           paths:
             - venv
       - run:
           name: Run unit tests
           command: |
             . venv/bin/activate
             nosetests -v
       - run:
           name: Check source code style
           command: |
             . venv/bin/activate
             flake8 --exclude=venv
