#!/bin/sh

LOG_CONFIG_FILE="./conf/log.ini"

while getopts d OPT
do
  case $OPT in
    "d" ) LOG_CONFIG_FILE="./conf/log_debug.ini" ;;
  esac
done

cd `dirname $0`/..
PYTHONPATH=`pwd` ryu-manager flowsieve.authenticator --log-config-file=$LOG_CONFIG_FILE

